name: Build image
on:
  push:
    branches:
      - master
jobs:
  build_image:
    # ubuntu-latest is too old (ubuntu-latest == ubuntu-18.04)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Prepare files
        run: |
          make prep
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: christophebedard/ade-powerline-shell
          tags: latest
          labels: ade_image_commit_sha=${{ github.sha }}
          add_git_labels: true
